### ISSUE TITLE
[Bug]: generate button unresponsive in webUI then ^C OOM after a while

### ISSUE THREAD

**Issue by G-force78** [deforum-art/sd-webui-text2video#88] opened 2023-03-31 10:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

Set to 128x128 12 frames, cfg 7, steps 20. 
Generate button doesnt seem to work but collab shows something happening
```
Git commit: d16d9d47 (Thu Mar 30 09:18:56 2023)
Starting text2video
Pipeline setup
config namespace(framework='pytorch', task='text-to-video-synthesis'.....

```
Not particularly high RAM
![modelscoperam](https://user-images.githubusercontent.com/114336644/229096693-dd4da917-c567-450e-a81e-04ec754ab547.jpg)

### Steps to reproduce the problem

1. Go to .... modelscope tab
2. Press .... generate
3. ... wait for error message

### What should have happened?

produced short video

### WebUI and Deforum extension Commit IDs

webui commit id - a9eab236d7e8afa4d6205127904a385b2c43bb24
txt2vid commit id - d16d9d47

### What GPU were you using for launching?

Tesla T4, 15360 MiB, 15101 MiB

### On which platform are you launching the webui backend with the extension?

Google Colab (Other)

### Settings

...............

### Console logs

```Shell
.........
```

**Comment by kabachuha** [comment] 2023-04-14 15:03
duplicate of https://github.com/deforum-art/sd-webui-text2video/issues/64

**Closed by kabachuha** 2023-04-14 15:03 UTC
Labels: bug
